name: Poetry prerelease

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry --pip-args=--pre
    - run: poetry config virtualenvs.prefer-active-python true
    - uses: actions/setup-python@main
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'poetry'
    - run: poetry install
    - run: python -V
    - run: poetry run python -V
